### ISSUE TITLE
Update zoom center anchor correctly when zoomed in

### ISSUE THREAD

**Issue by iver56** [ninjadev/renin#40]
Scenario:
1. Zoom in
2. Scroll horizontally
3. Zoom in/out

Expected: Zoom anchor is now centered at the center the user sees
Actual: Zoom center is global center?

**Comment by stianjensen** [comment]
> Actual: Zoom center is global center?

I think the zoom anchor is the playhead, actually. But having it be the center of your current screen at all times might be better. Or possibly the position of the mouse cursor.
